### ISSUE TITLE
The API of inclusive/exclusive ranges in select/3 is a bit problematic

### ISSUE THREAD

**Issue by Qqwy** [lucaong/cubdb#3]
Currently, changing whether `min_key:` and `max_key:` are inclusive or exclusive is changed by wrapping the key you want to match on by `{your_key, :excluded}`. 

I think this interface could be improved, since it conflicts when someone tries to e.g. use a `{:key, :excluded}` as key. Also, it will silently fail (and not match any keys it was expected to match) if someone mistypes `:excluded`.

I think a better approach would be to have extra options to toggle between inclusive and exclusive, for instance named `min_key_inclusive: true`, or `min_key_settings: [exclusive: true]`.

**Comment by lucaong** [comment]
Hi, thanks a lot for opening a discussion on this.

I thought about it too. Using the long form should be always safe (in case the key is literally `{:xyz, :excluded}` the long form would be `{{:xyz, :excluded}, :included}`), but I agree it’s not ideal. Also, yes, misspellings should cause explicit errors.

Your idea to use `min_key_exclusive:` sounds good. I just wonder if `min_key:` should be inclusive by default, or if it’s better to be explicit and only accept either `min_key_inclusive` or `min_key_exclusive`. I slightly lean for the first option (`min_key` or `min_key_exclusive`), because I suspect that the inclusive case is the most common and a reasonable default.

What’s your opinion?

**Comment by Qqwy** [comment]
I agree. Half-open ranges (so inclusive min-key and exclusive max-key) are, as far as I am aware, the most wide-spread and commonly used ranges in computing science and software engineering.

**Comment by lucaong** [comment]
What I mean, is something like this:

```elixir
CubDB.select(db, [
  min_key: :foo,
  max_key_exclusive: :bar
])
```

**Comment by Qqwy** [comment]
Ah!

I had a slightly different idea in mind, namely:

```
CubDB.select(db, [
  min_key: {:foo, 42},
  min_key_exclusive: true,
  max_key: {:foo, 1234},
  max_key_exclusive: false
])
```
or possibly:

```
CubDB.select(db, [
  min_key: {:foo, 42},
  min_key_settings: [exclusive: true],
  max_key: {:foo, 1234},
  max_key_settings: [exclusive: false]
])
```

**Comment by lucaong** [comment]
After (a lot of) thinking, I feel that your proposal is the clearest and simplest:

```elixir
// All inclusive by default
{:ok, result} = CubDB.select(db, [
  min_key: {:foo, 123},
  max_key: {:bar, 321}
]))

// Setting min/max key to nil means literal nil
{:ok, result} = CubDB.select(db, [
  min_key: nil,
  max_key: {:bar, 321}
]))

// To leave the range open, omit min/max key
{:ok, result} = CubDB.select(db, [
  max_key: {:bar, 321}
]))

// Make boundaries exclusive by setting min/max_key_inclusive to false
{:ok, result} = CubDB.select(db, [
  min_key: {:foo, 123},
  max_key: {:bar, 321},
  max_key_inclusive: false
]))
```

I will soon implement this. It will be a breaking change, but it's good to improve this part of the API before version 1.

Thanks a lot for the feedback!

**Comment by lucaong** [comment]
The new version [v0.13.0](https://github.com/lucaong/cubdb/releases/tag/v0.13.0) is published on Hex, introducing the improved API.
