### ISSUE TITLE
no function clause error

### ISSUE THREAD

**Issue by Sebisnow** [lucaong/cubdb#6]
Hi,
I use cubdb 0.13.0 to log a few metrics of a website test with hound. I just encountered the following error on trying to read the metrics with:

```
iex(7)> {:ok, db} = CubDB.start_link("/opt/pisa_load_test")
{:ok, #PID<0.238.0>}
iex(8)> CubDB.get(db, :load_test) 
```

The error:
```
    16:15:28.668 [error] Task #PID<0.242.0> started from #PID<0.238.0> terminating
** (FunctionClauseError) no function clause matching in CubDB.Btree.lookup_leaf/4
    (cubdb) lib/cubdb/btree.ex:316: CubDB.Btree.lookup_leaf({:v, [%{action: :long_running_request, date: ~U[2019-09-30 13:57:17.803671Z], duration: 442, env: :test, request_count: 120}, %{action: :mailbox, date: ~U[2019-09-30 13:49:55.251067Z], duration: nil, env: :test, request_count: 100}, %{action: :login, date: ~U[2019-09-30 13:49:47.146515Z], duration: 5, env: :test, request_count: 81}, %{date: ~U[2019-09-20 08:46:37.453455Z], env: :int, results: [%{login: %{duration: 9, request_count: 78}, long_running_request: %{duration: 23, request_count: 104}}]}, %{date: ~U[2019-09-20 08:12:58.613462Z], env: :int, results: [%{login: %{duration: 11, request_count: 79}, long_running_request: %{duration: 22, request_count: 106}}]}, %{date: ~U[2019-09-19 14:29:40.151420Z], env: :test, results: [%{login: %{duration: 6, request_count: 81}, long_running_request: %{duration: 34, request_count: 109}}]}, %{date: ~U[2019-09-19 14:27:07.536142Z], env: :test, results: [%{login: %{duration: 6, request_count: 83}, long_running_request: %{duration: 34, request_count: 110}}]}]}, %CubDB.Store.File{file_path: "/opt/pisa_load_test/0.cub", pid: #PID<0.239.0>}, :load_test, [])
    (cubdb) lib/cubdb/btree.ex:106: CubDB.Btree.fetch/2
    (cubdb) lib/cubdb/reader.ex:31: CubDB.Reader.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &CubDB.Reader.run/4
    Args: [{#PID<0.211.0>, #Reference<0.1265108072.3161718785.70643>}, #PID<0.238.0>, %CubDB.Btree{capacity: 32, dirt: 14, root: {:v, [%{action: :long_running_request, date: ~U[2019-09-30 13:57:17.803671Z], duration: 442, env: :test, request_count: 120}, %{action: :mailbox, date: ~U[2019-09-30 13:49:55.251067Z], duration: nil, env: :test, request_count: 100}, %{action: :login, date: ~U[2019-09-30 13:49:47.146515Z], duration: 5, env: :test, request_count: 81}, %{date: ~U[2019-09-20 08:46:37.453455Z], env: :int, results: [%{login: %{duration: 9, request_count: 78}, long_running_request: %{duration: 23, request_count: 104}}]}, %{date: ~U[2019-09-20 08:12:58.613462Z], env: :int, results: [%{login: %{duration: 11, request_count: 79}, long_running_request: %{duration: 22, request_count: 106}}]}, %{date: ~U[2019-09-19 14:29:40.151420Z], env: :test, results: [%{login: %{duration: 6, request_count: 81}, long_running_request: %{duration: 34, request_count: 109}}]}, %{date: ~U[2019-09-19 14:27:07.536142Z], env: :test, results: [%{login: %{duration: 6, request_count: 83}, long_running_request: %{duration: 34, request_count: 110}}]}]}, root_loc: 12305, size: 0, store: %CubDB.Store.File{file_path: "/opt/pisa_load_test/0.cub", pid: #PID<0.239.0>}}, {:get, :load_test, nil}]
** (EXIT from #PID<0.211.0>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in CubDB.Btree.lookup_leaf/4
        (cubdb) lib/cubdb/btree.ex:316: CubDB.Btree.lookup_leaf({:v, [%{action: :long_running_request, date: ~U[2019-09-30 13:57:17.803671Z], duration: 442, env: :test, request_count: 120}, %{action: :mailbox, date: ~U[2019-09-30 13:49:55.251067Z], duration: nil, env: :test, request_count: 100}, %{action: :login, date: ~U[2019-09-30 13:49:47.146515Z], duration: 5, env: :test, request_count: 81}, %{date: ~U[2019-09-20 08:46:37.453455Z], env: :int, results: [%{login: %{duration: 9, request_count: 78}, long_running_request: %{duration: 23, request_count: 104}}]}, %{date: ~U[2019-09-20 08:12:58.613462Z], env: :int, results: [%{login: %{duration: 11, request_count: 79}, long_running_request: %{duration: 22, request_count: 106}}]}, %{date: ~U[2019-09-19 14:29:40.151420Z], env: :test, results: [%{login: %{duration: 6, request_count: 81}, long_running_request: %{duration: 34, request_count: 109}}]}, %{date: ~U[2019-09-19 14:27:07.536142Z], env: :test, results: [%{login: %{duration: 6, request_count: 83}, long_running_request: %{duration: 34, request_count: 110}}]}]}, %CubDB.Store.File{file_path: "/opt/pisa_load_test/0.cub", pid: #PID<0.239.0>}, :load_test, [])
        (cubdb) lib/cubdb/btree.ex:106: CubDB.Btree.fetch/2
        (cubdb) lib/cubdb/reader.ex:31: CubDB.Reader.run/4
        (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```

At the same time the program testing a website might write data. Somehow the database got corrupted. do have any idea how this could have happened?

**Comment by lucaong** [comment]
Hi @Sebisnow , thanks a lot for reporting this. Sorry for the delay, I was really busy with other projects and I somehow missed the notification on this one.

It seems that the `lookup_leaf` function unexpectedly encounters a value node instead of an internal `Btree` node (branch or leaf). The value node is well formatted, so I would exclude a file corruption problem. I am looking into this to figure out how this could happen.

Do you have any more detail to share with me? Was this a recurring issue or it happened just once? If recurring, do you have any hint what triggered it? What kind of settings are you using (autocompaction, etc.), and which operations do you perform?

I realize this issue was opened quite soe time ago, but any information would be precious 🙂

**Comment by lucaong** [comment]
Interesting information I get from your logs:
  - No compaction has happened (file is `0.cub`)
  - The value node (`{:v, ...}`) is the `Btree` root, which should never be the case (root should be either a branch or a leaf node)
  - The `Btree` has size 0, so it looks like the value node is somehow there instead of an empty root leaf node.

This might be enough information for me to debug this issue.

**Comment by lucaong** [comment]
Hi @Sebisnow ,
I run more tests and double-checked the code, but I could not identify any issue that could cause this. I might need some more help from you to zero in on the cause.

One question: did you start several `CubDB` processes using the same data directory at the same time? It's important to run only one `CubDB` process, because running multiple ones at the same time can corrupt the db file. Multiple Elixir processes can call the same `CubDB` process concurrently, that's perfectly OK and `CubDB` will handle the concurrent access, but there should be only one `CubDB` process per data directory at any time. Multiple processes writing on the same data dir could have caused this issue, and I should probably make it more clear in the documentation and README.

If that was not the case though, I'd be really grateful if you could give me more context on the issue, like if it was a recurring one, what operations were you using (`put`, `delete`, `put_multi`, etc.) and which settings. Anything that you can remember could be important.

**Comment by Sebisnow** [comment]
Hi @lucaong,

Thanks for your effort. It is possible, that I started the `CubDB` process twice instead of using the already opened one. It  is possible that I ran the before mentioned hound tests at the same time that I wanted to gather and aggregate the statistics. So this was probably my fault entirely.
I basically just called `put` and `get`, so nothing advanced or error prone there.
Thank you very much for your help!

**Comment by lucaong** [comment]
Thanks a lot for your help @Sebisnow ! Feel free to reopen this if you run into any issue again. On my side, I should make the documentation clearer, and maybe find a way to prevent multiple `CubDB` processes to be started on the same data dir (something akin to lock files).
