### ISSUE TITLE
How to sort uuid or string?

### ISSUE THREAD

**Issue by drselump14** [lucaong/cubdb#72]
Hi, thanks for making this cool library. 
I wonder how to model data from another server in which the ID is UUID/Hashid (string, non-integer).
I was thinking about modeling  the key of the data by 

```
{:message, uuid}
```

But then I get stuck on how to sort the data.
For an integer id, it would be like

```
select(min_key: {:message, 0}, max_key: {:message, nil})
```

but how about an uuid/hashid(string) ? Any help would be appreciated

**Comment by lucaong** [comment]
Hi @drselump14 , thanks for the kind words :)

If you want to select all entries from this collection, considering the [term ordering](https://hexdocs.pm/elixir/1.12/operators.html#term-ordering), you could do:

```elixir
select(min_key: {:message, ""}, max_key: {:message, 0, 0})
```

This should work because:

  - Tuples are compared by size, then by content, so a three-element tuple is always greater than a two-element tuple
  - Binary strings are always greater than lists
  - Numbers are always considered smaller than other terms

Technically the boundaries are not perfect, because for example the range will include `{:message, "hello", -1}`, but if you control how keys are structured and can ensure no such key is created, it should be good enough.

If Elixir had a concept of infinity, one could set  `max_key: {:message, -infinity, -infinity}`, but no such thing exists as far as I am aware.

**Comment by optikfluffel** [comment]
For UUIDs you could maybe also use the [Nil and Omni UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Special_UUIDs) as `min_key` and `max_key`.

**Comment by lucaong** [comment]
That makes a lot of sense @optikfluffel 🙂

**Comment by lucaong** [comment]
@drselump14 I will close the issue as the question is answered, but feel free to comment further, and I will reopen it if needed.

**Comment by zachallaun** [comment]
This particular use-case has been addressed, but I wanted to offer a refinement based on @lucaong's comment above that is a bit more flexible and works with arbitrary binaries that don't have a known min-max like UUIDs.

Let's say you have keys that look like this:

```elixir
{:A, :category1, "foo"}
{:A, :category2, "bar"}
{:B, :category3, "baz"}
```

Now here's the question: how do you select all `:A` keys in `:category1`?

You could use `{:A, :category1, ""}` as a min key, but you cannot construct a max key using the techniques above that will not include unnecessary additional data.

For instance, you could try increasing the tuple length and use `{:A, :category1, 0, 0}` as suggested above, but this will end up selecting our `{:A, :category2, ...}` and `{:B, ..., ...}` records because the size-4 tuple is greater than all size-3 tuples. 

The solution we found is to wrap binaries in tuples! So now our keys look like this:

```elixir
{:A, :category1, {"foo"}}
{:A, :category2, {"bar"}}
{:B, :category3, {"baz"}}
```

And we can select using the min/max keys:

```elixir
{:A, :category1, {}}
{:A, :category1, {nil, nil}}
```

This allows us to select exactly the range that we want! As a bonus, this can be applied to any field in your key to create a natural min/max so that you don't have to remember a bunch of factoids about term order :). For instance, if we wrap categories, we could get all `:A` records with these min/max keys:

```elixir
{:A, {}, nil}
{:A, {nil, nil}, nil}
```

**Comment by lucaong** [comment]
Nice!

**Comment by drselump14** [comment]
thanks @lucaong @zachallaun
